name: erp_mobile_cnplus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.3.4
  http: ^1.4.0
  fl_chart: ^1.0.0
  flutter_svg: ^2.0.7
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_charts: ^20.2.47
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.0
  connectivity_plus: ^6.1.5
  logger: ^2.6.1
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/sales.png
    - assets/products.png
    - assets/purchase.png

